---
apiVersion: v1
kind: Service
metadata:
  name: bee
  namespace: staging
  labels:
    helm.sh/chart: bee-0.9.10
    app.kubernetes.io/name: bee
    app.kubernetes.io/instance: bee
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - name: api
      port: 80
      protocol: TCP
      targetPort: api
  selector:
    app.kubernetes.io/instance: bee
    app.kubernetes.io/name: bee
  type: ClusterIP
