image:
  repository: ethersphere/bee
  tag: latest
  pullPolicy: Always

replicaCount: 1

serviceAccount:
  create: true

singlePodSts:
  enabled: true
  labelFilter: bee-staging

# podLabels:
#  - bzz.ethswarm.org/fund: "true"

ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/limit-rpm: "5"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "2"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/session-cookie-name: "SWARMGATEWAY"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "86400" # 1 day
    nginx.ingress.kubernetes.io/session-cookie-path: "default"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "7200"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($scheme = http) {
        return 301 https://$server_name$request_uri;
      }
      location = / {
        proxy_pass https://ethswarm-core.s3.amazonaws.com/gateway/index.html;
      }
  ingressClassName: nginx
  pathType: Prefix
  hosts:
    - domain: staging.ethswarm.org
      paths:
        - /
      tlsSecret: staging-ethswarm-org-wildcard-cert
  tls: true

ingressDebug:
  enabled: true
  ingressClassName: nginx-internal
  pathType: Prefix
  hosts:
    - domain: staging.internal
      paths:
        - /

resources:
  limits:
    memory: 2Gi
    cpu: 1.5
  requests:
    memory: 1Gi
    cpu: 0.75

persistence:
  enabled: true
  size: 34Gi
  storageClass: local-storage

nodeSelector:
  node-group: staging

updateStrategy:
  type: RollingUpdate

beeConfig:
  bootnode: "/dnsaddr/staging.ethswarm.org"
  debug_api_enable: true
  full_node: true
  gateway_mode: false
  network_id: 5
  usePasswordFile: true
  existingSecret: bee-password
  tracing_enable: true
  tracing_endpoint: jaeger-operator-jaeger-agent.observability:6831
  resolver_options: "https://cloudflare-eth.com"
  swap_enable: true
  swap_endpoint: wss://goerli.infura.io/ws/v3/3e88bb0189ea44c0904699e0dfff5641
  swap_deployment_gas_price: 1500000000000
  swap_initial_deposit: 1000000000000000000
  verbosity: 5

libp2pSettings:
  enabled: true
  existingSecret: bee-libp2pkeys

p2pFixedPort:
  enabled: true
