---
# Source: prometheus-pushgateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pushgateway-infra-test
  labels:
    app: infra-test
    chart: prometheus-pushgateway-1.4.2
    heritage: Helm
    release: pushgateway-infra-test
---
# Source: prometheus-pushgateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pushgateway-infra-test
  annotations:
    {}
  labels:
    app: infra-test
    chart: prometheus-pushgateway-1.4.2
    heritage: Helm
    release: pushgateway-infra-test
spec:
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app: infra-test
    release: pushgateway-infra-test
---
# Source: prometheus-pushgateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway-infra-test
  labels:
    app: infra-test
    chart: prometheus-pushgateway-1.4.2
    heritage: Helm
    release: pushgateway-infra-test
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: infra-test
      release: pushgateway-infra-test
  template:
    metadata:
      labels:
        app: infra-test
        release: pushgateway-infra-test
      annotations:
        {}
    spec:
      serviceAccountName: pushgateway-infra-test
      containers:
        - name: pushgateway
          image: "prom/pushgateway:v1.2.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
            {}
---
# Source: prometheus-pushgateway/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pushgateway-infra-test
  namespace: monitoring
  labels:
    app: infra-test
    chart: prometheus-pushgateway-1.4.2
    heritage: Helm
    release: pushgateway-infra-test
spec:
  endpoints:
  - port: http
    interval: 1s
    path: /metrics
    honorLabels: true
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: infra-test
      release: pushgateway-infra-test
