---
# Source: beekeeper/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: infra-test-beekeeper
  name: beekeeper
  labels:

    helm.sh/chart: beekeeper-0.1.5
    app.kubernetes.io/name: beekeeper
    app.kubernetes.io/instance: beekeeper
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
