name: Infra Test

on:
  repository_dispatch:
    types: [trigger-install]

jobs:
  helm-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Generate k8s yamls
        run: |
          helm repo add ethersphere https://ethersphere.github.io/helm
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm template pushgateway-infra-test -n monitoring prometheus-community/prometheus-pushgateway -f infra-test/pushgateway.yaml --no-hooks > infra-test/pushgateway/all.yaml
          helm template geth-swap -n infra-test-geth ethersphere/geth-swap -f infra-test/geth.yaml --no-hooks > infra-test/geth/all.yaml
          helm template beekeeper -n infra-test-beekeeper ethersphere/beekeeper -f infra-test/beekeeper.yaml --no-hooks > infra-test/beekeeper/all.yaml
          helm template bee -n infra-test ethersphere/bee -f infra-test/bee.yaml --no-hooks > infra-test/bee/all.yaml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "install infra-test"
          commit_author: bee-worker <bee-worker@ethswarm.org>
