name: Infra Test

on:
  repository_dispatch:
    types: [trigger-uninstall]

jobs:
  helm-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Remove k8s yamls
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | DESIRED_VERSION=v3.2.0 bash
          helm repo add ethersphere https://ethersphere.github.io/helm
          helm repo update
          rm infra-test/infra-test-create.yaml infra-test/infra-test-check.yaml || true
          helm template beekeeper-infra-test-delete -n infra-test ethersphere/beekeeper -f infra-test-delete.yaml --no-hooks > infra-test/infra-test-delete.yaml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "uninstall infra-test"
          commit_author: bee-worker <bee-worker@ethswarm.org>
          commit_user_name: bee-worker
          commit_user_email: bee-worker@ethswarm.org
