name: Infra Test

on:
  repository_dispatch:
    types: [trigger-uninstall]

jobs:
  helm-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Remove k8s yamls
        run: |
          docker run --rm -v "${PWD}":/workdir mikefarah/yq:3.3.4 yq read infra-test/infra-test-create-job.yaml > infra-test/infra-test-create-sa.yaml
          docker run --rm -v "${PWD}":/workdir mikefarah/yq:3.3.4 yq read infra-test/infra-test-check-job.yaml > infra-test/infra-test-check-sa.yaml
          rm infra-test/*-job.yaml || true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "uninstall infra-test"
          commit_author: bee-worker <bee-worker@ethswarm.org>
          commit_user_name: bee-worker
          commit_user_email: bee-worker@ethswarm.org
