name: Argo

on:
  repository_dispatch:
    types: [trigger-argo]

jobs:
  helm-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Generate k8s yamls
        run: |
          helm repo add ethersphere https://ethersphere.github.io/helm
          helm repo update
          helm template bee -n bee ethersphere/bee -f edge-bee.yaml --no-hooks --set image.digest=${{ github.event.client_payload.digest }} > edge/bee.yaml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "commit: ${{ github.event.client_payload.sha }} digest: ${{ github.event.client_payload.digest }}"
          commit_author: bee-worker <bee-worker@ethswarm.org>
