name: Argo

on:
  repository_dispatch:
    types: [trigger-argo]

jobs:
  helm-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Generate k8s yamls
        run: |
          # curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | DESIRED_VERSION=v3.2.0 bash
          helm repo add ethersphere https://ethersphere.github.io/helm
          helm repo update
          for i in {0..19}; do helm template bee-$i -n staging ethersphere/bee -f staging.yaml --no-hooks --set p2pFixedPort.nodePortStart=$(( 31000+$i )) --set image.digest=${{ github.event.client_payload.digest }} > staging/bee-$i.yaml; done
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "commit: ${{ github.event.client_payload.sha }} digest: ${{ github.event.client_payload.digest }}"
          commit_author: bee-worker <bee-worker@ethswarm.org>
          commit_user_name: bee-worker
          commit_user_email: bee-worker@ethswarm.org
